[package]
name = "graphtest"
version = "0.1.0"
authors = ["Jan Kleinert <jan.kleinert@dlr.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
